name: First Workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo"Hi, This is the practice repo for the github action- workflow"
      - name: Print goodbye
        run: echo"Good bye"
      
